// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7qrrNZv6KTPIxajsXGUCgi_0HdVllGcw',
    appId: '1:306130832127:web:652d273c9d26d15e541aca',
    messagingSenderId: '306130832127',
    projectId: 'larry-food-app',
    authDomain: 'larry-food-app.firebaseapp.com',
    databaseURL: 'https://larry-food-app-default-rtdb.firebaseio.com',
    storageBucket: 'larry-food-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACikGbkwRkOgE9EVxVc0CoDfkSXenuymw',
    appId: '1:306130832127:android:339b0175dd7667f9541aca',
    messagingSenderId: '306130832127',
    projectId: 'larry-food-app',
    storageBucket: 'larry-food-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeBfH2tCyNInwaSN3oB3X4PM9TKwHOe6E',
    appId: '1:306130832127:ios:fa77a4292c32ac48541aca',
    messagingSenderId: '306130832127',
    projectId: 'larry-food-app',
    databaseURL: 'https://larry-food-app-default-rtdb.firebaseio.com',
    storageBucket: 'larry-food-app.appspot.com',
    iosClientId: '306130832127-8iou5f8mt77n56vn5b7lnjeebgvjcl6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
